Lagt til konfigurasjon og klient mot familie-tilbake.
navikt/familie-ef-iverksett pull request #190
Opened 2021-10-13 12:45 UTC by bent-lorentzen

2021-10-14 10:59 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/tilbakekreving/TilbakekrevingClient.kt
> +    fun finnBehandlinger(fagsakId: UUID): List<Behandling> {
Trenger vi `finnBehandlinger` i iverksett, eller er det egentlige noe som ef-sak kun trenger? 
Eller kommer iverksett være en proxy for alle kall mot tilbake?

2021-10-14 14:17 UTC, ma10s requested changes
fagsakId - tror dette er en Long (eksternid)

2021-10-14 14:45 UTC, ma10s approved these changes
Takk for fin kode - her skal det kopieres :)

2021-10-15 11:24 UTC, bent-lorentzen commented on src/main/kotlin/no/nav/familie/ef/iverksett/tilbakekreving/TilbakekrevingClient.kt
> +class TilbakekrevingClient(@Qualifier("azure") restOperations: RestOperations,
Eksterne.

2021-10-15 12:28 UTC, merged