Fjernet interne nøkler fra oversending til DVH.
navikt/familie-ef-iverksett pull request #288
Opened 2022-01-05 16:41 UTC by bent-lorentzen

2022-01-05 16:52 UTC, blommish reviewed
Er dette ønskelig? Skjønner att vi kanskje burde sende dem noe annet enn våre interne nøkler, men har det så mye å si att vi burde endre det? Tenker nesten dette burde vært prioritert inn i køn som en favrooppgave? 

1. Breaking change, vi lagrer json i databasen og tidligere versjon har andre typer? 
2. Er det avstemt med DVH?

2022-01-05 18:30 UTC, bent-lorentzen commented
> Er dette ønskelig? Skjønner att vi kanskje burde sende dem noe annet enn våre interne nøkler, men har det så mye å si att vi burde endre det? Tenker nesten dette burde vært prioritert inn i køn som en favrooppgave?
> 
> 1. Breaking change, vi lagrer json i databasen og tidligere versjon har andre typer?
> 2. Er det avstemt med DVH?

Sånn det er nå, så sender vi en blanding av eksterne og interne nøkler, så dvh får ikke koblet behandlingene. Dette er en prodfeil nå, så jeg så det som en hasteoppgave.
1. Dette er grunnen til at vi valgte å lage tabeller av json-strukturen i saksbehandling; for å unngå braking changes. Vi kan selvfølgelig endre tilbake til String, da vil vi vel unngå braking changes, og så får vi håpe at folk forstår at de ikke skal lagre uuid i String.
2. Ja.

2022-01-06 07:38 UTC, blommish commented
> > Er dette ønskelig? Skjønner att vi kanskje burde sende dem noe annet enn våre interne nøkler, men har det så mye å si att vi burde endre det? Tenker nesten dette burde vært prioritert inn i køn som en favrooppgave?
> > 
> > 1. Breaking change, vi lagrer json i databasen og tidligere versjon har andre typer?
> > 2. Er det avstemt med DVH?
> 
> Sånn det er nå, så sender vi en blanding av eksterne og interne nøkler, så dvh får ikke koblet behandlingene. Dette er en prodfeil nå, så jeg så det som en hasteoppgave.
> 
> 1. Dette er grunnen til at vi valgte å lage tabeller av json-strukturen i saksbehandling; for å unngå braking changes. Vi kan selvfølgelig endre tilbake til String, da vil vi vel unngå braking changes, og så får vi håpe at folk forstår at de ikke skal lagre uuid i String.
> 2. Ja.

1. Skjønte ikke helt hva du mener med første setting. Man vill alltid kunne ha breaking changes, uavhengig av hvordan man lagrer data. 
Men hvis man fortsetter å lagre eksterne-kontrakter som strings, så er det ingen direkt breaking change i kontraktet. 
(2)Ser også att BA bruker strings til desse typene. Tror også det kan ha blitt en litt missforståelse i tråden i dvh-kanalen, du spør om vi kan sende numeriskt i stedet, mulig de tolker det som att vi ikke endrer noe på kontraktet men fortsatt sender string? 

Hva gjør vi med data som allerede er sendt? 

Husk att det er fint å oppgi i commit-melding/pr hva det er man prøver å løse, gjerne med link til favro/slack så att PR gir litt kontekst. Er veldig vanskelig å skjønne en slik PR uten kontekst. 
EKs i dette tilfelle så er det fint å oppgi att DVH trenger våre eksterne nøkler for å kunne linke sammen behandlinger tvers fagsystem.

2022-01-06 07:39 UTC, blommish requested changes
Setter denne til request changes til vi har oppklart denne.

2022-01-07 09:56 UTC, blommish approved these changes
Ser ene DVH-teamet sa att de støttet denne. Antar att det andra teamet også har den samma funksjonalitet for å lese fra kafka?

2022-01-07 12:58 UTC, charliemidtlyng commented on src/main/kotlin/no/nav/familie/ef/iverksett/vedtakstatistikk/BehandlingDVHMapper.kt
>                               tidspunktVedtak = iverksett.vedtak.vedtakstidspunkt.atZone(ZoneId.of("Europe/Oslo")),
Har vi kontaktet vedtaksstatistikk-gjengen? Det er noen andre enn gjengen i `#dvh-ptsak-ensligforsorger`

2022-01-12 10:46 UTC, merged