Vil bruke bestillingsId i exceptionbody ved 409 (Conflict) når vi dis…
navikt/familie-ef-iverksett pull request #600
Opened 2022-10-27 11:04 UTC by ma10s

…tribuerer brev (Allerede distribuert).

Exception eksempel 
no.nav.familie.http.client.RessursException: org.springframework.web.client.HttpClientErrorException$Conflict: 409 Conflict: "{"data":null,"status":"FEILET","melding":"409 : \"{\"bestillingsId\":\"50417d42-3bf9-43cb-8b11-06bfdf3d56bd\"}\"","frontendFeilmelding":null

osv

2022-10-27 11:11 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                frittståendeBrev = lagreEndringerPåDistribuerbrevResultat(frittståendeBrev, journalpostResultat, bestillingId, frittståendeBrevId)
Prøvde fjerne "frittståendeBrev" retur her, men da klaget mange av testene...

2022-10-27 11:12 UTC, ma10s commented on src/test/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTaskTest.kt
> +                BrevdistribusjonConflictExceptionResponseBody(
Ganske usikker på om denne er heeelt riktig. 
Kan kanskje gjøre et forsøk på å teste i preprod også.

2022-10-27 14:28 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +        return frittståendeBrevOppdatert
inline?

2022-10-27 14:28 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                    return OK
return er inne i en forEach her? Kanskje ikke gir forventet resultat hvis nr 1 av 3 får 409? :)

2022-10-27 14:28 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/BrevdistribusjonConflictExceptionResponseBody.kt
> +data class BrevdistribusjonConflictExceptionResponseBody(val bestillingsId: String)
Kanskje er tilstrekkelig med `Brevdistribusjonskonflikt` ? 
```suggestion
data class Brevdistribusjonskonflikt(val bestillingsId: String)
```

2022-10-27 14:28 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                frittståendeBrev = lagreEndringerPåDistribuerbrevResultat(frittståendeBrev, journalpostResultat, bestillingId, frittståendeBrevId)
Ja, den oppdaterer vel frittståendeBrev her med det nye journalpostresultatet, sånn at neste iterasjon gjenbruker det samme resultatet, hadde kunnet brukt fold i stedet forEach

2022-10-27 14:44 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                        lagreEndringerPåDistribuerbrevResultat(
Her må vel også frittståendeBrev settes? 
Litt usikker på om lesingen av `responseBodyAsString` kommer å virke som forventet, prøv å kalle, burde gå å teste å fjerne en journalpost fra resultat i databasen, og rekjøre en task som har gått ok fra før

2022-10-27 14:50 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                        lagreEndringerPåDistribuerbrevResultat(
Eller bare logge cause.responseBodyAsString først, for å sjekke at du får dataen som du forventer.

Cause er cause på exception, se eks https://logs.adeo.no/app/discover#/doc/tjenestekall-*/tjenestekall-team-teamfamilie-prod-000021?id=d4wXGIQBfIaqcZmNSxEB

Jeg tror du nog må gjøre noe i integrasjoner for at dette skal virke :) Kanskje legge inn Brevdistribusjonskonflikt i felles kontrakter?

2022-10-27 16:44 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                frittståendeBrev = lagreEndringerPåDistribuerbrevResultat(frittståendeBrev, journalpostResultat, bestillingId, frittståendeBrevId)
Mulig det blir bedre å flytte try/catch inn i distribuer brev (på samme måte som distribuer vedtaksbrev.

2022-10-28 08:08 UTC, ma10s commented
Testet i preprod. Funnet feil. Jobber med fiks.

2022-10-31 09:48 UTC, blommish requested changes

2022-10-31 09:48 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                e.ressurs.melding
Er dette riktig?

2022-10-31 09:51 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                        e.ressurs.melding // TODO oppdater med "noe". Denne er ferdig
?

2022-10-31 09:54 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                    frittståendeBrevRepository.oppdaterDistribuerBrevResultat(
Det er 2 metoder med mange argument som kalles både i try og catch, som burde kunne trekkes ut i egen metode, eks

```kotlin
private fun oppdaterFrittståendeBrevOgLagreResultat(
        frittståendeBrev: FrittståendeBrev,
        journalpostResultat: JournalpostResultat,
        bestillingId: String
    ): FrittståendeBrev {
        val oppdatertFrittståendeBrev = oppdaterFrittståendeBrev(
            frittståendeBrev,
            journalpostResultat,
            bestillingId
        )
        frittståendeBrevRepository.oppdaterDistribuerBrevResultat(
            oppdatertFrittståendeBrev.id,
            oppdatertFrittståendeBrev.distribuerBrevResultat
        )
        return oppdatertFrittståendeBrev
    }
```

2022-10-31 10:07 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                        e.ressurs.melding // TODO oppdater med "noe". Denne er ferdig
Alt som skal til på en bestillingId er en string. Body fra dok forsvinner på veien (integrasjoner)

Denne meldingen vil være => 
409 : "{"bestillingsId":"50417d42-3bf9-43cb-8b11-06bfdf3d56bd"}

Ikke veldig vakkert - og database vil se litt rar ut (se beskrivelse)

2022-10-31 10:10 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                e.ressurs.melding
Tja - det er et definisjonsspørsmål. Vi får ikke data fra dokdist (den mister vi i integrasjoenr) det vi har igjen her er denne meldingen 

409 : "{"bestillingsId":"50417d42-3bf9-43cb-8b11-06bfdf3d56bd"}

Ikke veldig pent, men alt som kreves er en streng. 

Vurderte en hardkodet string: "Konflikt fra dokdist. Bestillingsid ikke tilgjengelig, men alt ok"

2022-10-31 11:09 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                e.ressurs.melding
Hvis vi noen gang skal gjøre noe med denne dataen så blir det litt rart hvis vi i noen tilfeller har data som dataen på et annet format?

2022-10-31 11:15 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                e.ressurs.melding
Det er ju ikke sikkert at integrasjoner kommer returnere bestillingsId i meldingen, så kan ju være fint å parsea dataen likevel, sånn at vi helt pluteslig ikke lagrer noen annen rar data der :)

2022-10-31 13:04 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                e.ressurs.melding
Enig. Hvis vi gjør det vi gjør ovenfor kan vi si at vi har "gitt opp" å gjøre noe med denne dataen i framtiden. Men er det egentlig viktig data? Og kan bestillingsId brukes til noe? 

bestillingsId brukes ikke til noe i vårt system. Eneste funksjon denne har er kanskje å kunne svare ut spørsmålet: "har dere sendt brevet?" kan vi si - "jada, vi har en bestillingsId". Ut over det kunne denne kolonnen vært en boolean true/false i databasen. 

Jeg har ikke lyst til å parse "melding" ovenfor. Da vil jeg heller legge inn data på ressursen i integrasjoner?

2022-11-04 07:30 UTC, blommish approved these changes
:thumbs

2022-11-04 07:30 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/DistribuerVedtaksbrevTask.kt
> +                objectMapper.readValue<DistribuerJournalpostResponseTo>(e.ressurs.data.toString(), DistribuerJournalpostResponseTo::class.java).bestillingsId
Småpirk, men med import av `import com.fasterxml.jackson.module.kotlin.readValue` (som vi bruker ellers) så kan man endre denne raden
```suggestion
                objectMapper.readValue<DistribuerJournalpostResponseTo>(e.ressurs.data.toString()).bestillingsId
```

2022-11-04 07:30 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
> +                    ).bestillingsId
```suggestion
                    val bestillingsId =
                        objectMapper.readValue<DistribuerJournalpostResponseTo>(e.ressurs.data.toString()).bestillingsId
```

2022-11-04 07:30 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/brev/frittstående/DistribuerFrittståendeBrevTask.kt
>                  if (cause is HttpClientErrorException.Gone) {
If her burde kanskje blitt bytt ut med when når det er 3 caser

2022-11-04 11:19 UTC, merged