Fremleggsoppgave inntekt
navikt/familie-ef-iverksett pull request #690
Opened 2023-03-08 12:44 UTC by throndi

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11507

2023-03-08 14:04 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/FremleggsoppgaveService.kt
> +    fun skalOppretteFremleggsoppgave(iverksett: IverksettOvergangsstønad): Boolean {
Då opprettOppgave burde kunne være en del av oppgaveservice så tenker jeg denne ikke trenger å være i en egen service

2023-03-08 14:04 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +        const val TYPE = "opprettFremleggsOppgaveForOvergangsstønadTask"
```suggestion
        const val TYPE = "opprettFremleggsOppgaveForOvergangsstønad"
```

2023-03-08 14:04 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +            logger.info("Opprettet fremleggsoppgave for behandling=$behandlingId oppgaveID=$oppgaveId")
Småpirk, `oppgave` eller `oppgaveId`
```suggestion
            logger.info("Opprettet fremleggsoppgave for behandling=$behandlingId oppgave=$oppgaveId")
```

2023-03-08 14:04 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +            logger.info(
Fint med logging 👍

2023-03-08 14:24 UTC, throndi commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/FremleggsoppgaveService.kt
> +        return when {
Ok, sjekker på det viset

2023-03-08 14:42 UTC, throndi commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/fremleggsoppgaveinntekt/FremleggsoppgaveService.kt
> +    fun opprettFremleggsoppgave(iverksett: IverksettOvergangsstønad): Long {
Opprettet en "opprettOppgave" i stedet

2023-03-09 09:20 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +            val oppgaveId = oppgaveService.opprettOppgave(iverksett.data, Oppgavetype.Fremlegg, "Inntekt")
Burde oppgaven ha noe mer enn kun "Inntekt" som beskrivelse? 👀

2023-03-09 09:29 UTC, throndi commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OppgaveService.kt
> +        return tilkjentYtelse?.let { it.andelerTilkjentYtelse.any { it.beløp > 0 } } ?: false
Hvis personen har 0 i stønadsbeløp / utbetaling, da skal det ikke opprettes oppgave ?

2023-03-09 09:30 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +            val oppgaveId = oppgaveService.opprettOppgave(iverksett.data, Oppgavetype.Fremlegg, "Inntekt")
Virket på Mirja som att dette var riktig

2023-03-09 09:31 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OppgaveService.kt
> +        return tilkjentYtelse?.let { it.andelerTilkjentYtelse.any { it.beløp > 0 } } ?: false
Hva er målet med selve fremleggningsoppgaven?

2023-03-09 09:34 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OppgaveService.kt
> +        return tilkjentYtelse?.let { it.andelerTilkjentYtelse.any { it.beløp > 0 } } ?: false
Har sjekket denne med Mirja også, det er fordi det ikke finnes noen risiko for feilutbetaling når det er 0 i beløp. 
Kan være fint å kanskje få inn en kommentar om det på denne metoden?

2023-03-09 14:17 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OppgaveService.kt
> +        return tilkjentYtelse?.andelerTilkjentYtelse?.any { it.beløp > 0 } ?: false
Høres fornuftig ut å filtrere bort "gamle perioder" før vi sjekker, men heller en oppgave for mye enn en oppgave for lite?

2023-03-09 14:21 UTC, ma10s requested changes
Bra jobba Trond! 

Tror vi må ta en ny gjennomgang av "skal/skal ikke" opprette oppgave etter innspill fra saksbeh. (se slack tråd) - saksbehandler får mulighet til å velge å ikke lage oppgave.  

Da må vi kanskje ha mer logikk i sak/sak-frontend og legger mer ansvar på saksbehandler. Vi tar en prat om dette i morgen 👍

2023-03-10 08:14 UTC, throndi commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OpprettFremleggsOppgaveForOvergangsstønadTask.kt
> +            val oppgaveId = oppgaveService.opprettOppgave(iverksett.data, Oppgavetype.Fremlegg, "Inntekt")
Jepp

2023-03-10 14:17 UTC, blommish commented on src/main/kotlin/no/nav/familie/ef/iverksett/oppgave/OppgaveService.kt
> +        return tilkjentYtelse?.andelerTilkjentYtelse?.any { it.beløp > 0 } ?: false
Det er noen få tegn som måtte inn, så det føles veldig unødvendig. Men nå skal vel denne løses på en annen måte..

2023-03-21 13:05 UTC, closed without merging